services:
  frappe:
    image: frappe/bench:latest
    user: "frappe"
    working_dir: /home/frappe
    command: ["/bin/bash","-lc","/workspace/init.sh"]
    environment:
      SHELL: /bin/bash
      SITE_NAME: hrms.localhost
      ADMIN_PASSWORD: admin
      DB_TYPE: mariadb

      # MariaDB (Railway TCP proxy)
      DB_HOST: trolley.proxy.rlwy.net
      DB_PORT: "51999"
      DB_ROOT_USER: root                  # or your super user on Railway
      DB_ROOT_PASSWORD: "CYI-Vi3_B_4Ndf7C1e3.usRHOuU_zkRU"

      # Redis (your screenshot)
      REDIS_CACHE_URL:    "redis://default:TUwUwNxPhXtoaysMLvnyssapQWtRbGpz@nozomi.proxy.rlwy.net:46645"
      REDIS_QUEUE_URL:    "redis://default:TUwUwNxPhXtoaysMLvnyssapQWtRbGpz@nozomi.proxy.rlwy.net:46645"
      REDIS_SOCKETIO_URL: "redis://default:TUwUwNxPhXtoaysMLvnyssapQWtRbGpz@nozomi.proxy.rlwy.net:46645"

    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "9000:9000"
