services:
  frappe:
    image: frappe/bench:latest
    working_dir: /home/frappe
    # Normalize CRLF then run (Windows-safe)
    command: bash -lc 'sed -i "s/\r$//" /workspace/init.sh && chmod +x /workspace/init.sh && bash /workspace/init.sh'
    environment:
      SHELL: /bin/bash
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
